### ISSUE TITLE
compile patch 

### ISSUE THREAD

**Issue by GuillaumeLeNost** [pingdynasty/OwlServer#79] opened 2015-07-20 21:02 UTC
on staging website, with the testgiom patch which should compile ok, i have the following message:
PHP Fatal error:  Class 'MongoClient' not found in /var/www/hoxtonowl.com/subdomains/staging/patch-builder/patch-builder.php on line 230.

**Comment by samuele-artuso** [comment] 2015-07-21 10:45
This is an issue with the staging server (and it doesn't affect the live website).

Unfortunately there isn't much I can do about it for now—the staging server is broken and I've asked @pingdynasty to get me a new one.

**Comment by pingdynasty** [comment] 2015-07-21 12:21
It's not going to be today - maybe tomorrow!

**Comment by pingdynasty** [comment] 2015-07-26 19:36
Live site compiler is partly working - it's compiling succesfully, but the wrong patch...
I think it's receiving some default options instead of the right ones.
Are you setting PATCHNAME ?

**Comment by samuele-artuso** [comment] 2015-07-26 20:21
How do I reproduce the issue?

**Comment by pingdynasty** [comment] 2015-07-26 20:44
At the moment Compile always produces the same output, which is the Template patch binary (default when PATCHNAME is not specified).
You only get the patch name from the binary when you load it on the device, which makes it difficult to reproduce. However compiling different patches should yield syx files of different length and content.

**Comment by pingdynasty** [comment] 2015-07-26 20:55
I've got an idea: I will enable more Makefile output to stdout.

Compiling Stereo Delay now shows:
```
make[1]: Entering directory `/opt/OwlProgram.online'
echo Building patch "Template"
Building patch Template
echo "REGISTER_PATCH("Template"Patch, \""Template"\", 2, 2);" > /tmp/owl-patch-lgzJOl/patch.cpp
echo "#include \""Template"Patch.hpp\"" > /tmp/owl-patch-lgzJOl/patch.h
echo '.string "'"Template"'"' > /tmp/owl-patch-lgzJOl/progname.s
make[1]: Leaving directory `/opt/OwlProgram.online'
INFO: make exit code is 0.
INFO: Build successful!
```

Looks like env variables aren't set or not passed on. PATCHNAME, PATCHFILE and PATCHCLASS are all set to defaults, PATCHIN and PATCHOUT too. But BUILD seems correct.

You can also look at the intermediary files to see what's going on.
The file `patch.cpp` should have PATCHCLASS, PATCHNAME, PATCHIN and PATCHOUT in it.

**Comment by samuele-artuso** [comment] 2015-08-05 17:59
The patch builder script is now working on both ulrike and nestor.

I recompiled a few patches (9 of them, to be exact) and double checked that all the `.syx` files had different sizes and MD5 sums.

FYi, I'm building patches with a commands like this:

    make BUILD='/tmp/owl-build-b7Jmmv' PATCHSOURCE='/tmp/owl-src-uskr5T' PATCHFILE='BitH8rPatch.hpp' PATCHNAME='Contest/BitH8r' PATCHCLASS='BitH8rPatch' PATCHIN=2 PATCHOUT=2 sysex

The `patch-builder.php` script can output the individual command used for each patch by adding the `--show-build-cmd` command line option, e.g.:

    php patch-builder.php --name='Contest/BitH8r' --show-build-cmd

Hopefully, this should make it easier to find bugs.

I was a bit anal and I checked that the same files are output by ulrike and nestor for the same patch. Among the patches I tried, all the files are the same (in size and MD5 sum) apart from 'Four Band EQ': for this patch two different `.syx` files get built on each server—they have the same size in bytes but different MD5 sums. Could it be a bug?

**Comment by pingdynasty** [comment] 2015-08-05 18:52
cool, good work.
Is there an easy way to run the script to rebuild all patches, e.g. at 2 min intervals as discussed? If yes pls go ahead and start it.

Four band EQ: It's fine! The patch details are different. I updated it to stereo and didn't change it on staging.

**Comment by samuele-artuso** [comment] 2015-08-05 19:47
> on staging website, with the testgiom patch which should compile ok, i have the following message:
PHP Fatal error: Class 'MongoClient' not found in /var/www/hoxtonowl.com/subdomains/staging/patch-builder/patch-builder.php on line 230.

This is now fixed.

@pingdynasty, could you point `staging.hoxtonowl.com` to the public IP address of urlike?

**Comment by pingdynasty** [comment] 2015-08-06 14:03
I've updated the CNAME to point to ulrike.pingdynasty.com

**Comment by pingdynasty** [comment] 2015-08-12 14:02
@samuele-artuso : the menu bar links on staging.hoxtonowl.com go to ulrike.pingdynasty.com, which is wrong (try logging in).

**Comment by samuele-artuso** [comment] 2015-08-12 14:09
Fixed.

**Closed** 2015-08-12 14:31 UTC
